const quizData = [
  {
    question: "Which language runs in a web browser?",
    answer_1: "Java",
    answer_2: "C",
    answer_3: "Python",
    answer_4: "JavaScript",
    correct: "answer_4",
  },
  // {
  //   question: "What does CSS stand for?",
  //   answer_1: "Central Style Sheets",
  //   answer_2: "Cascading Style Sheets",
  //   answer_3: "Cascading Simple Sheets",
  //   answer_4: "Cars SUVs Sailboats",
  //   correct: "answer_2",
  // },
  // {
  //   question: "What does HTML stand for?",
  //   answer_1: "Hypertext Markup Language",
  //   answer_2: "Hypertext Markdown Language",
  //   answer_3: "Hyperloop Machine Language",
  //   answer_4: "Helicopters Terminals Motorboats Lamborginis",
  //   correct: "answer_1",
  // },
  // {
  //   question: "What year was JavaScript launched?",
  //   answer_1: "1996",
  //   answer_2: "1995",
  //   answer_3: "1994",
  //   answer_4: "none of the above",
  //   correct: "answer_2",
  // },
  // {
  //   question: "Who is the current CEO of Google ?",
  //   answer_1: "Sunder Pichai",
  //   answer_2: "Larry Page ",
  //   answer_3: "Jhon Brown",
  //   answer_4: "Jeffry Black",
  //   correct: "answer_1",
  // },
  // {
  //   question: "Who is the current CEO of Amazon ?",
  //   answer_1: "Jeff Bezos",
  //   answer_2: "Warren Buffet ",
  //   answer_3: "Andy Jassy",
  //   answer_4: "Tom Klington",
  //   correct: "answer_3",
  // },
  // {
  //   question: "Who is the current CEO of Tesla ?",
  //   answer_1: "Jeffry Black",
  //   answer_2: "Elon Musk ",
  //   answer_3: "Jhon Brown",
  //   answer_4: "Warren Buffet ",
  //   correct: "answer_2",
  // },
  // {
  //   question: "Who is the current CEO of Microsoft ?",
  //   answer_1: "Satya Nadella ",
  //   answer_2: "Tom Klington",
  //   answer_3: "Jhon Brown",
  //   answer_4: "Andy Jassy",
  //   correct: "answer_1",
  // },
  // {
  //   question: "Which of the company is owned by Mark Zkerburg ?",
  //   answer_1: "Neuralink ",
  //   answer_2: "Meta Platforms Inc ",
  //   answer_3: "Metaverse LLC ",
  //   answer_4: "Tom Klington",
  //   correct: "answer_2",
  // },
  {
    question:"Which built-in method returns the string representation of the numbers value?",
    answer_1: "toValue()",
    answer_2: "toNumber()",
    answer_3: "toString()",
    answer_4: "None of the above.",
    correct: "answer_2",
  },
];
export default quizData;
